#startcode DockerCompose
version: "3"
services:   
    sender:
        image: sender
        build:
            context: ./Sender/
            dockerfile: Dockerfile
        depends_on:
            - rabbitmq
    receiver:
        image: receiver
        build:
            context: ./Receiver/
            dockerfile: Dockerfile
        depends_on:
            - rabbitmq
    rabbitmq:
        image: "rabbitmq:3-management"
        ports:
            - "15672:15672"
#endcode