# startcode compose
version: "3.8"
services:   
    sender:
        image: sender
        build:
            context: .
            dockerfile: ./Sender/Dockerfile
        depends_on:
            - rabbitmq
    receiver:
        image: receiver
        build:
            context: .
            dockerfile: ./Receiver/Dockerfile
        depends_on:
            - rabbitmq
    rabbitmq:
        image: "rabbitmq:3.8-management"
        ports:
            - "15672:15672"
            - "5672:5672"
        healthcheck:
            test: ["CMD-SHELL", "if rabbitmqctl status; then \nexit 0 \nfi \nexit 1"]
            interval: 10s
            retries: 5
# endcode            