version: '3.8'
services:

  error:
    image: particular/servicecontrol.azureservicebus.init-windows:4
    ports:
      - 33333:33333
    volumes:
      - error:c:/data
      - C:/ProgramData/ParticularSoftware:C:/ProgramData/ParticularSoftware
    env_file: environment.env

  monitoring:
    image: particular/servicecontrol.azureservicebus.monitoring.init-windows:4
    ports:
      - 33633:33633
    volumes:
      - C:/ProgramData/ParticularSoftware:C:/ProgramData/ParticularSoftware
    env_file: environment.env

  audit:
    image: particular/servicecontrol.azureservicebus.audit.init-windows:4
    ports:
      - 44444:44444
    volumes:
      - audit:c:/data
      - C:/ProgramData/ParticularSoftware:C:/ProgramData/ParticularSoftware
    env_file: environment.env






volumes:
  error:
  audit:
